### PR TITLE
doc/attributes: Add a note regarding filtering behavior with associat…

### PR DESCRIPTION
**Pull request by elthariel**
…ions

Sorry for the formatting change, didn't want to touch my emacs config, just for a few lines editing :p

### CODE REVIEW

**Comment by elthariel** [comment]
Ping @yosiat 💌

**Comment by yosiat** [comment]
@elthariel sorry for the delay

**Comment by yosiat** [comment]
@elthariel both this PR and https://github.com/yosiat/panko_serializer/pull/60 are deployed and available in the docs.

**Comment by elthariel** [comment]
Absolutely no worries :) I know the deal

**Comment by elthariel** [comment]
Thanks :)

**Pull request merged**
